# Wk2 Trk3, Day 1
<br>

# Exercises: NumPy
---
<br>

#### CSAA2022

Welcome to the first half of today's lab! In this lab, we are going to practice the fundamentals of numpy by creating arrays, accessing elements, subsetting using Boolean indexing and finally, we are also going to practice some well known numpy functions. 


Of course, we are not able to cover it all and as such we recommend the online resouces below. As always, documentation is your friend, so make sure you have a look if uncertain. 

Useful references: 
* [Official NumPy reference ](https://numpy.org/doc/stable/reference/index.html)
* [Cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)


In [42]:
#first step if we want to use functions that have been already implemented in a library is to import that library

#traditional way of importing numpy
import numpy as np

#### Task 1: Mastering the basics

##### Part A: Create some arrays


* Create an array from the following list 
        sample_list = [1.0,4.0,9.0,23.0]

* **Do not use** *np.array* for the next problems: 
    * create a 10 x 10 matrix of all ones
    * a 15 element vector, with all elements equal to np.pi
    * an 1D array with elements between 0 and 50, stepping by 2
    * an array of random numbers of 0 mean and unit std; choose the size yourselves 
    * create an array of even numbers between 100 and 500 and then divide it by 2





In [43]:
### YOUR CODE GOES HERE
sample_list = [1.0,4.0,9.0,23.0]
array1 = np.array(sample_list)
print(array1)

[ 1.  4.  9. 23.]


In [44]:
array2 = np.ones((10, 10))
print(array2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [45]:
# help(np.full)
array3 = np.full((15,), np.pi)
print(array3)

[3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265
 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265
 3.14159265 3.14159265 3.14159265]


In [5]:
array4 = np.arange(0, 50, 2)
print(array4)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


In [6]:
# help(np.random)
array5 = np.random.randn(25).reshape((5,5))
print(array5)

[[-0.67339345  0.0348867  -0.68236675 -2.12463887  1.70904918]
 [ 0.08532176 -0.74124389  1.60759899 -0.92508804 -0.08057866]
 [ 1.26940341  3.29985899 -0.32221851  0.25386407  0.59886152]
 [-0.30202059 -2.27214308 -0.06679518  0.02295828 -0.34617425]
 [-0.48022127  0.04534328 -0.31775965 -0.20959985  1.1338176 ]]


In [7]:
array6 = np.arange(100, 500, 2)
array7 = array6 // 2
print(array6)
print(array7)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170
 172 174 176 178 180 182 184 186 188 190 192 194 196 198 200 202 204 206
 208 210 212 214 216 218 220 222 224 226 228 230 232 234 236 238 240 242
 244 246 248 250 252 254 256 258 260 262 264 266 268 270 272 274 276 278
 280 282 284 286 288 290 292 294 296 298 300 302 304 306 308 310 312 314
 316 318 320 322 324 326 328 330 332 334 336 338 340 342 344 346 348 350
 352 354 356 358 360 362 364 366 368 370 372 374 376 378 380 382 384 386
 388 390 392 394 396 398 400 402 404 406 408 410 412 414 416 418 420 422
 424 426 428 430 432 434 436 438 440 442 444 446 448 450 452 454 456 458
 460 462 464 466 468 470 472 474 476 478 480 482 484 486 488 490 492 494
 496 498]
[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95 

##### Part B: Practing indexing and slicing

Given the array below, access the following elements:

* access 39 using negative indexing
* slice the first five elements of each row
* slice the numbers between 0 and 5
* slice all the odd numbers (use Boolean indexing)

In [46]:
test1 = np.arange(0,40).reshape(2,20)
print(test1)
print(test1[-1,-1])
print(test1[ : ,0:5])
print(test1[test1 <= 5])
print(test1[test1%2!=0])

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]]
39
[[ 0  1  2  3  4]
 [20 21 22 23 24]]
[0 1 2 3 4 5]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


#### Task 2: Snails

The snails data can be found in the dataLab folder. 

Groups of 20 snails were held for periods of 1, 2, 3 or 4 weeks in carefully controlled conditions of temperature
and relative humidity. The two species of snails are labelled as 0 and 1. At the end of the exposure time the snails were tested to see if
they had survived.

Data format, 6 columns as follows: 
    * species (0 or 1)
    * exposure (weeks)
    * humidity
    * temperature
    * ndeaths
    * nsnails (initial number at the start)
    
    
    
**What you need to do**: 

* Read the data. Use numpy!
* Practice indexing and slicing: 
        * temperature of last entry
        * humidity of the 5th entry
        * get 2nd and 3rd column
        * get the first 5 rows
        
* Compute the following: 
        * total number of deaths :(
        * total number of snails that survived :)
        * max temperature
        * mean humidity
        * average death rate 
* Split the snails in 2 arrays based on their species
* Which group of snails has the highest average death rate? 
* What are the optimum living conditions (temperature and humidity) for snails? Use only snails kept for the full duration of the experiment. 


In [9]:
# help(np.loadtxt)
# reading the 
snails_array = np.loadtxt("labData/snails.txt")
# print(snails_array)
last_temp = snails_array[-1, 3]
print(last_temp)
_5th_hum = snails_array[4, 2]
print(_5th_hum)
col_2nd_3rd = snails_array[:, 1:3]
# print(col_2nd_3rd)
row_5 = snails_array[:5]
print(row_5)

20.0
65.8
[[ 0.   1.  60.  10.   0.  20. ]
 [ 0.   1.  60.  15.   0.  20. ]
 [ 0.   1.  60.  20.   0.  20. ]
 [ 0.   1.  65.8 10.   0.  20. ]
 [ 0.   1.  65.8 15.   0.  20. ]]


In [10]:
test = np.ones((3,5))
test.sum(axis=0)

array([3., 3., 3., 3., 3.])

In [51]:
total_no_deaths = snails_array[:, -2].sum(axis=0)
print(total_no_deaths)
array_no_survived = snails_array[:, -1] - snails_array[:, -2]
total_no_survived = array_no_survived.sum(axis=0)
print(total_no_survived)
total_no_survived = snails_array[:, -1].sum(axis=0) - snails_array[:, -2].sum(axis=0)
print(total_no_survived)
temp_col = snails_array[:,3]
max_temp = temp_col.max(axis=0)
print(max_temp)
hum_col = snails_array[:,2]
mean_hum = hum_col.mean(axis=0)
print(mean_hum)
average_death_rate = snails_array[:, -2].sum(axis=0) / snails_array[:, -1].sum(axis=0)
print(average_death_rate)
snails_array[:, -2].sum()

275.0
1645.0
1645.0
20.0
68.02499999999999
0.14322916666666666


275.0

In [49]:
species_0 = snails_array[snails_array[:, 0]==0.0]
# print(species_0)
species_1 = snails_array[snails_array[:, 0]==1.0]
# print(species_1)
species_0_death_rate = species_0[:, -2].sum(axis=0) / species_0[:, -1].sum(axis=0)
species_1_death_rate = species_1[:, -2].sum(axis=0) / species_1[:, -1].sum(axis=0)
print(species_0_death_rate)
print(species_1_death_rate)


death_rate_per_group = snails_array[:, -2] / snails_array[:, -1]
group_with_heightes_death_rate = death_rate_per_group.argmax()
print(group_with_heightes_death_rate)

full_exposure_array = snails_array[snails_array[:, 1]==4.0]
group_with_highest_survival = full_exposure_array[:,-2].argmin()
print(snails_array[group_with_highest_survival, 2:4])

0.08541666666666667
0.20104166666666667
86
[75.8 10. ]
